name: "Hello GitHub Actions Mentees"

on:
  workflow_dispatch:

jobs:
  say_hello_job:
    runs-on: ubuntu-latest  # The runner environment (Ubuntu in this case)

    steps:
      - name: Echo Hello Mentees
        run: echo "Hello, Mentees!"

