name: 06 Passing Data Between Steps
on:
  workflow_dispatch:

jobs:
  info-sharring:
    runs-on: ubuntu-22.04
    steps:
      - name: Create data
        id: user
        # this step will set the output name for this step to Michal
        run: |
          echo "name=Michal" >> $GITHUB_OUTPUT

      - name: Receive data
        run: | 
          echo ${{ steps.user.outputs.name }}
