name: input-dispatch
on:
  workflow_dispatch:
    inputs:
      name:
        default: "Jwala"
        description: "Name to greet"
jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello ${{inputs.name }}"
