name: 04 workflow_dispatch

on:
  workflow_dispatch:
    inputs:
      username:
        description: 'Username'
        default: 'Jwala'
        required: true
        type: string
      position:
        description: 'Position'
        required: true
        type: number

jobs:
  echo-username-age:
    runs-on: ubuntu-latest
    steps:
        name: Echo Username
        run: echo "Username: ${{ inputs.username }}"
        name: echo position
        run:  echo "position: ${{ inputs.position }}"
