name: sequential jobs
on:
  push:
  workflow_dispatch:

jobs:
  development:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Deploy to the development environment
        run: echo "Insert deployment steps below..."
  test:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - name: Deploy to the development environment
        run: echo "Insert deployment steps below..."

  production:
    runs-on: ubuntu-latest
    environment: production
    needs: [development, test]
    steps:
      - name: Deploy to the production environment
        run: echo "Insert deployment steps below..."
