name: Install VSCode and MSBuild

on: [workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest  # GitHub Actions Windows runner

    steps:
    - name: Install VSCode via Chocolatey
      run: |
        choco install vscode -y  # Install VSCode silently
    - name: Check MSBuild
      run: |
        msbuild -version  # Verify MSBuild is available
