name: Install VSCode and MSBuild

on: [workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest  # This runner has MSBuild and Visual Studio already

    steps:
    - name: Set up Visual Studio Code
      run: |
        # Download and install VSCode
        Invoke-WebRequest -Uri https://update.code.visualstudio.com/latest/win32-x64-user/stable -OutFile vscode_installer.exe
        Start-Process -FilePath vscode_installer.exe -Args '/silent' -Wait
        Remove-Item vscode_installer.exe -Force

    - name: Check MSBuild
      run: |
        # Check if MSBuild is available
        msbuild -version
